import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { MantineProvider } from '@mantine/core'

import { describe, expect, it } from 'vitest'
import HomePage from './HomePage'
import PageHeader from '@/components/PageHeader'

const root = join(process.cwd(), 'components', 'home')

describe('homepage theme contract', () => {
  it('keeps the route entry server-side and delegates to the client homepage', async () => {
    const page = await readFile(join(process.cwd(), 'app', 'page.tsx'), 'utf8')
    const homePage = await readFile(join(root, 'HomePage.tsx'), 'utf8')

    expect(page).toContain("import HomePage from '@/components/home/HomePage'")
    expect(page).toContain('return <HomePage />')
    expect(page).not.toContain("'use client'")
    expect(homePage).toContain("'use client'")
    expect(homePage).toContain("useComputedColorScheme('dark')")
    expect(homePage).toContain('useMantineColorScheme()')
    expect(homePage).toContain('onToggleTheme={toggleColorScheme}')
    expect(homePage).not.toContain('<PageHeader theme=')
    expect(homePage).not.toContain('data-home-theme')
    expect(homePage).not.toContain('useStudioStore')
    expect(homePage).toContain('The Revolutionized Art of Hanzi')
    expect(homePage).toContain('href="/studio"')
    expect(homePage).toContain('<PageBg theme={theme} />')
    expect(homePage).toContain('h="calc(100dvh - 72px)"')
    expect(homePage).toContain('className={classes.ctaPosition} pos="absolute" bottom={64}')
  })

  it('bootstraps Mantine color scheme before hydration with an inline script', async () => {
    const layout = await readFile(join(process.cwd(), 'app', 'layout.tsx'), 'utf8')

    expect(layout).not.toContain('ColorSchemeScript')
    expect(layout).toContain('<Script id="mantine-color-scheme" strategy="beforeInteractive">')
    expect(layout).toContain("['light', 'dark', 'auto'].includes(publicEnv.defaultColorScheme)")
    expect(layout).toContain('window.localStorage.getItem("mantine-color-scheme-value")')
    expect(layout).toContain('_colorScheme === "light"')
    expect(layout).toContain('_colorScheme === "dark"')
    expect(layout).toContain('_colorScheme === "auto"')
    expect(layout).toContain('window.matchMedia("(prefers-color-scheme: dark)").matches')
    expect(layout).toContain('data-mantine-color-scheme')
    expect(layout).toContain('} catch (e) {}')
    expect(layout).toContain('suppressHydrationWarning')
  })

  it('renders one spatial GPU artwork instead of blob or HUD motion', async () => {
    const background = await readFile(join(process.cwd(), 'components', 'PageBg.tsx'), 'utf8')

    expect(background).toContain('HomeSpatialMotion')
    expect(background).toContain('classes.ambientField')
    expect(background).toContain('classes.motionCanvas')
    expect(background).toContain('aria-hidden="true"')
    expect(background).not.toContain('MotionSvg')
    expect(background).not.toContain('classes.techField')
    expect(background).not.toContain('classes.orbitSystem')
    expect(background).not.toContain('classes.scanBand')
  })

  it('builds a bounded atmospheric shader field with pointer response and SVG stroke texture', async () => {
    const motion = await readFile(join(root, 'HomeSpatialMotion.tsx'), 'utf8')
    const strokeLayout = await readFile(join(root, 'homeStrokeLayout.tsx'), 'utf8')

    expect(motion).toContain('navigator.gpu')
    expect(motion).toContain('GPUCanvasContext')
    expect(motion).toContain('let device: GPUDevice | null')
    expect(motion).toContain('let uniformBuffer: GPUBuffer | null')
    expect(motion).toContain('let trailTextures: GPUTexture[]')
    expect(motion).toContain('GPURenderPipeline')
    expect(motion).toContain('GPUBindGroup[]')
    expect(motion).not.toContain('GPUBufferLike')
    expect(motion).not.toContain('GPUTextureLike')
    expect(motion).not.toContain('GPUDeviceLike')
    expect(motion).not.toContain('GPURenderPipelineLike')
    expect(motion).not.toContain('as unknown as GPUDevice')
    expect(motion).toContain('requestAdapter')
    expect(motion).toContain('createRenderPipeline')
    expect(motion).toContain('queue.writeBuffer')
    expect(motion).toContain('onSubmittedWorkDone')
    expect(motion).toContain("canvas.dataset.ready = 'true'")
    expect(motion).toContain("canvas.dataset.strokeReady = 'true'")
    expect(motion).toContain("delete canvas.dataset.strokeReady")
    expect(motion).toContain('@vertex')
    expect(motion).toContain('@fragment')
    expect(motion).toContain('draw(3)')
    expect(motion).toContain('ResizeObserver')
    expect(motion).toContain('resizeFrameHandle')
    expect(motion).toContain('maskDebounceTimer')
    expect(motion).toContain('pendingMaskJob')
    expect(motion).toContain('job.generation !== strokeMaskGeneration')
    expect(motion).toContain('strokeMaskGeneration += 1')
    expect(motion).toContain('device?.destroy()')
    expect(motion).toContain('cancelAnimationFrame')
    expect(motion).toContain('uPointer')
    expect(motion).toContain('uPreviousPointer')
    expect(motion).toContain('trailFeedbackShader')
    expect(motion).toContain('createTexture')
    expect(motion).toContain("format: 'rgba8unorm'")
    expect(motion).toContain('previousTrail')
    expect(motion).toContain('trailTextures')
    expect(motion).toContain('queue.writeTexture')
    expect(motion).toContain('serializeKaishuStrokeMaskSvg')
    expect(motion).toContain('binding: 3')
    expect((motion.match(/uStrokeMaskReady: f32/g) ?? [])).toHaveLength(2)
    expect(motion).toContain('let warpedUv')
    expect(motion).toContain('textureSample(strokeMask, linearSampler, warpedUv)')
    expect(motion).toContain('readTrailIndex')
    expect(motion).toContain('trailPass')
    expect(motion).toContain('atmospherePass')
    expect(motion).toContain('textureSample')
    expect(motion).toContain('blurRadius')
    expect(motion).toContain('let pressBlurDistance = length((input.uv - uniforms.uPressPointer) * aspect)')
    expect(motion).toContain('let pressBlurAmount =')
    expect(motion).toContain('let pressBlurScale = mix(')
    expect(motion).toContain('smoothstep(0.02, 0.28, uniforms.uPressStrength)')
    expect(motion).toContain('1.0 - smoothstep(0.06, 0.24, pressBlurDistance)')
    expect(motion).toContain('${TRAIL_BLUR_TEXELS} * pressBlurScale')
    expect(motion).toContain('liquify')
    expect(motion).toContain('distanceToSegment')
    expect(motion).toContain('capsule')
    expect(motion).toContain('uDeltaTime')
    expect(motion).toContain("feedback.b * exp(-0.12 * uniforms.uDeltaTime) - 0.16 * uniforms.uDeltaTime")
    expect(motion).toContain('uniforms.uPointerSpeed * uniforms.uDeltaTime')
    expect(motion).toContain('const maxPixelCount = 1_600_000')
    expect(motion).toContain('TRAIL_IDLE_RESET_MS = 5200')
    expect(motion).toContain("from './homeTrailMath'")
    expect(motion).toContain('${TRAIL_DIRECTION_DECAY}')
    expect(motion).toContain('${TRAIL_DIRECTION_DEADZONE}')
    expect(motion).toContain('${TRAIL_MAX_DISPLACEMENT}')
    expect(motion).toContain('${TRAIL_BLUR_TEXELS}')
    expect(motion).toContain(
      'size: { width: canvas.width, height: canvas.height, depthOrArrayLayers: 1 }'
    )
    expect(motion).not.toContain('canvas.width * 0.5')
    expect(motion).not.toContain('canvas.height * 0.5')
    expect(motion).toContain('textureDimensions(previousTrail)')
    expect(motion).toContain('atmosphereBindGroups[nextTrailIndex]')
    expect(motion).toContain(
      'return select(vec2f(0.0), direction, magnitude > ${TRAIL_DIRECTION_DEADZONE})'
    )
    expect(motion).toContain('mixedDirection / max(mixedMagnitude, 1.0)')
    expect(motion).toContain('mixedMagnitude > 1.0')
    expect(motion).not.toContain('direction / max(magnitude, 0.08)')
    expect(motion).not.toContain('mixedDirection / max(mixedMagnitude, 0.001)')
    expect(motion).not.toContain('if (pointerSpeed > 0.001)')
    expect(motion).toContain('pointerRef.current.lastMovedAt !== observedMoveStamp')
    expect(motion).toContain('lastPointerMoveTime = observedMoveStamp')
    expect(motion).toContain('idleTrailCleared')
    expect(motion).toContain('performance.now()')
    expect(motion).toContain('viscousPointer')
    expect(motion).toContain('voronoise')
    expect(motion).toContain('anchoredPalette')
    expect(motion).toContain('differenceBlend')
    expect(motion).toContain('screenBlend')
    expect(motion).toContain('amplifyChroma')
    expect(motion).toContain('subtleIridescence')
    expect(motion).toContain('trailIridescence')
    expect(motion).toContain('trailColorInfluence')
    expect(motion).toContain(
      'smoothstep(0.0, 0.52, trail.b * trailDirectionMagnitude)'
    )
    expect(motion).toContain('trailRainbowBand')
    expect(motion).toContain('smoothstep(0.0, 0.46, abs(trail.b - 0.45))')
    expect(motion).toContain('trailVisibility')
    expect(motion).toContain('smoothstep(0.0, 0.42, trail.b)')
    expect(motion).toContain('trailSpectrum')
    expect(motion).toContain('trailAxis')
    expect(motion).toContain('trailNormal')
    expect(motion).toContain('dot(rainbowPosition, trailAxis)')
    expect(motion).toContain('lightRainbowPhase')
    expect(motion).toContain('darkRainbowPhase')
    expect(motion).toContain('darkTrailIridescence')
    expect(motion).toContain('trailIridescence * trailRainbowBand')
    expect(motion).toContain('vividTrailColor * trailColorInfluence')
    expect(motion).toContain('darkRainbowTarget')
    expect(motion).toContain('darkRainbowMix')
    expect(motion).toContain('darkTrailIridescence, trailSpectrum, 0.4), 0.8')
    expect(motion).toContain('(0.65 + darkTrailLuminance * 0.42)')
    expect(motion).toContain('trailVisibility * 0.58 + trailRainbowBand * 0.28')
    expect(motion).toContain('darkRainbowTarget * darkRainbowMix * 1.48')
    expect(motion).toContain('lightRainbowTarget')
    expect(motion).toContain('lightRainbowMix')
    expect(motion).toContain('trailVisibility * 0.52 + trailRainbowBand * 0.28')
    expect(motion).toContain('lightAurora = mix(lightAurora, lightRainbowTarget, lightRainbowMix)')
    expect(motion).toContain('lightContourHighlight')
    expect(motion).toContain('lightHighlightColor')
    expect(motion).toContain(
      'lightAurora = screenBlend(lightAurora, lightHighlightColor * lightContourHighlight)'
    )
    expect(motion).toContain('(lightAurora - vec3f(0.5)) * 1.1 + vec3f(0.5)')
    expect(motion).toContain('lightThemeDarkSource')
    expect(motion).not.toContain('darkColor = screenBlend(darkColor, vividTrailColor')
    expect(motion).toContain('polarCenter')
    expect(motion).not.toContain('let polarAngle =')
    expect(motion).not.toContain('let polarUv =')
    expect(motion).not.toContain('polarDistortion')
    expect(motion).not.toContain('indigoOverlay')
    expect(motion).not.toContain('polarFlow')
    expect(motion).not.toContain('polarContour')
    expect(motion).toContain('primaryCell')
    expect(motion).toContain(
      'let lightBase = mix(vec3f(0.88, 0.94, 0.99), vec3f(0.97, 0.9, 0.99), staticTexture)'
    )
    expect(motion).toContain('lightDetailTint')
    expect(motion).toContain('var lightAurora = mix(lightBase, lightThemeDarkSource, 0.2)')
    expect(motion).toContain('lightAurora *= 1.0 - microTexture * 0.095')
    expect(motion).toContain('lightDetailTint = anchoredPalette(\n    staticTexture + 0.2,')
    expect(motion).toContain('staticRainbowColor')
    expect(motion).toContain('staticRainbowMix')
    expect(motion).toContain('staticRainbowSpectrum')
    expect(motion).toContain('staticRainbowSpectrum, 0.55')
    expect(motion).toContain('smoothstep(0.28, 0.78, primaryCell) * 0.14')
    expect(motion).toContain('lightAurora = mix(lightAurora, staticRainbowColor, staticRainbowMix)')
    expect(motion).toContain('staticHighlightField')
    expect(motion).toContain('staticHighlightBlocks')
    expect(motion).toContain('primaryCell * 0.72 + staticTexture * 0.28')
    expect(motion).toContain('0.38 + staticTexture * 0.2')
    expect(motion).toContain('clamp(staticHighlightBlocks, 0.0, 0.68)')
    expect(motion).toContain('microDot')
    expect(motion).toContain('uniforms.uResolution.y * 0.24')
    expect(motion).toContain('smoothstep(0.05, 0.16, length(cell))')
    expect(motion).toContain('0.26 + dither * 0.74')
    expect(motion).toContain('dither')
    expect(strokeLayout).toContain('getRandomValues')
    expect(strokeLayout).toContain('serializeKaishuStrokeMaskSvg')
    expect(motion).toContain('strokesRandomizedRef')
    expect(motion).toContain("strokeField.dataset.randomized = 'true'")
    expect(motion).toContain("querySelectorAll<SVGGElement>('[data-kaishu-stroke]')")
    expect(motion).toContain('--kaishu-stroke-width')
    expect(motion).toContain('getKaishuStrokePlacements')
    expect(motion).toContain('KaishuStrokePaths')
    expect(motion).toContain("addEventListener('pointermove'")
    expect(motion).toContain("removeEventListener('pointermove'")
    expect(motion).toContain("addEventListener('pointerdown'")
    expect(motion).toContain("removeEventListener('pointerdown'")
    expect(motion).toContain('pointerRef.current.pressX = x')
    expect(motion).toContain('pointerRef.current.pressY = screenY')
    expect((motion.match(/uPressStrength: f32/g) ?? [])).toHaveLength(2)
    expect((motion.match(/uPressPointer: vec2f/g) ?? [])).toHaveLength(2)
    expect(motion).toContain('pressDrawStrength')
    expect(motion).toContain('if (uniforms.uPressStrength > 0.0001)')
    expect(motion).toContain('let pressProgress = 1.0 - uniforms.uPressStrength')
    expect(motion).toContain(
      'let pressRadiusScale = mix(0.18, 0.78, smoothstep(0.0, 0.72, pressProgress))'
    )
    expect(motion).toContain(
      'let pressRadius = 0.14 * mix(aspectRatio, 1.0, 0.5) * pressRadiusScale'
    )
    expect(motion).toContain('let pressAngle = atan2(pressVector.y, pressVector.x)')
    expect(motion).toContain(
      'let pressOrganicPhase = dot(uniforms.uPressPointer, vec2f(5.1, 7.7))'
    )
    expect(motion).toContain('let pressOrganicRadius = pressRadius * (')
    expect(motion).toContain('sin(pressAngle * 3.0 + pressOrganicPhase) * 0.11')
    expect(motion).toContain('sin(pressAngle * 5.0 - pressOrganicPhase * 1.3) * 0.06')
    expect(motion).toContain(
      'let pressBrush = 1.0 - smoothstep(0.0, pressOrganicRadius * 1.35, pressDistance)'
    )
    expect(motion).toContain(
      'uniforms.uPressStrength * uniforms.uPressStrength * uniforms.uPressStrength'
    )
    expect(motion).toContain('pressFade * uniforms.uDeltaTime * 26.0)) * pressBrush')
    expect(motion).toContain('Math.exp(-pressAge / 260)')
    expect(motion).toContain('uniformFloats[12] = pointerRef.current.pressX')
    expect(motion).toContain('uniformFloats[13] = pointerRef.current.pressY')
    expect(motion).toContain('const uniformData = new ArrayBuffer(64)')
    expect(motion).toContain('pointerRef.current.y = screenY')
    expect(motion).toContain('0.5 - clipPosition.y * 0.5')
    expect(motion).toContain('destroy()')
    expect(motion).toContain('<svg')
    expect(strokeLayout).toContain('<path')
    expect(strokeLayout).not.toContain('<text')
    expect(strokeLayout).not.toMatch(/font-family|font-size/i)
    expect(motion).not.toContain('stroke-dasharray')
    expect(motion).not.toContain('strokeDasharray')
    expect(motion).not.toContain('prefers-reduced-motion')
    expect(motion).not.toContain('visibility')
    expect(motion).not.toContain('ShaderMaterial')
    expect(motion).not.toContain('@react-three/fiber')
    expect(motion).not.toContain('<Canvas')
    expect(motion).not.toContain('WebGL')
    expect(motion).not.toContain('MeshPhysicalMaterial')
    expect(motion).not.toContain('createCharacterMeshGeometries')
    expect(motion).not.toContain('SVGLoader')
    expect(motion).not.toContain("'/chars/")
    expect(motion).not.toContain('HUD')
    expect(motion).not.toContain('radar')
    expect(motion).not.toContain('scanBand')
  })

  it('renders the app dark default without nested CTA controls', () => {
    const markup = renderToStaticMarkup(
      createElement(MantineProvider, { defaultColorScheme: 'dark' }, createElement(HomePage))
    )

    expect(markup).not.toContain('data-home-theme')
    expect(markup).toContain('aria-label="Toggle color scheme"')
    expect(markup).not.toContain('aria-pressed')
    expect(markup).toMatch(/<a[^>]*href="\/studio"[^>]*>[\s\S]*?Open Studio[\s\S]*?<\/a>/)
    expect(markup).not.toMatch(/<a[^>]*href="\/studio"[^>]*>[\s\S]*?<button/)
  })

  it('renders stable header markup with both theme variants and one accessible logo name', () => {
    const renderHeader = () =>
      renderToStaticMarkup(
        createElement(
          MantineProvider,
          null,
          createElement(PageHeader, { onToggleTheme: () => undefined })
        )
      )
    const markup = renderHeader()

    expect(markup).toBe(renderHeader())
    expect(markup).toContain('logo.svg')
    expect(markup).toContain('logo-dark.svg')
    expect(markup).toContain('aria-label="Hanzi Studio"')
    expect(markup).toContain('aria-label="Toggle color scheme"')
    expect(markup).not.toContain('aria-pressed')
    expect(markup).not.toContain('>Theme<')
  })

  it('defines light and dark semantic tokens for the homepage surface and controls', async () => {
    const styles = await readFile(join(root, 'HomePage.module.css'), 'utf8')

    expect(styles).toContain(":global([data-mantine-color-scheme='light']) .home")
    expect(styles).toContain(":global([data-mantine-color-scheme='dark']) .home")
    expect(styles).toContain('--home-background-gradient:')
    expect(styles).toContain('#f7fbff 0%')
    expect(styles).toContain('linear-gradient(')
    expect(styles).toContain('135deg,')
    expect(styles).toContain('--home-title:')
    expect(styles).toContain('--home-cta-border:')
    expect(styles).toContain('--home-cta-surface:')
    expect(styles).toContain('--home-control-hover: rgba(104, 96, 164, 0.08);')
    expect(styles).toContain('--home-control-hover: rgba(151, 157, 204, 0.1);')
    expect(styles).toContain('--home-header-icon:')
    expect(styles).toContain('#05050d 100%')
    expect(styles).toContain('background: var(--home-background-gradient);')
    expect(styles).toContain('.ambientField')
    expect(styles).toContain('.ambientField::before')
    expect(styles).toContain('.ambientField::after')
    expect(styles).toContain('animation: ambient-color-flow-primary')
    expect(styles).toContain('animation: ambient-color-flow-secondary')
    expect(styles).toContain('will-change: transform, opacity')
    expect(styles).not.toContain('background-position:')
    expect(styles).toContain('--home-ambient-blue:')
    expect(styles).toContain('--home-ambient-green:')
    expect(styles).toContain('--home-ambient-indigo:')
    expect(styles).toContain("[data-mantine-color-scheme='light']) .home .ambientField::before")
    expect(styles).toContain('mix-blend-mode: multiply')
    expect(styles).toContain("[data-mantine-color-scheme='light']) .home .motionCanvas")
    expect(styles).toContain('opacity: 0.82')
    expect(styles).toContain('.motionCanvas')
    expect(styles).toContain('.motionSurface')
    expect(styles).toContain(".motionSurface[data-ready='true']")
    expect(styles).toContain(".motionSurface[data-stroke-ready='true']")
    expect(styles).toContain("+ .strokeField[data-randomized='true']")
    expect(styles).toContain('transition: opacity 900ms')
    expect(styles).toContain(".strokeField[data-randomized='true']")
    expect(styles).not.toContain('.dataPlane')
    expect(styles).not.toContain('.orbitSystem')
    expect(styles).not.toContain('.scanBand')
    expect(styles).toContain('.themeToggle:hover')
    expect(styles).toMatch(
      /\.themeToggle:hover,\s*\.headerIcon:hover\s*\{[^}]*background: var\(--home-control-hover\) !important/
    )
    expect(styles).toMatch(/\.ctaButton:hover\s*\{[^}]*background: var\(--home-cta-surface-hover\)/)
    expect(styles).toContain('.ctaButton:active')
    expect(styles).toContain('transform: translateY(-2px)')
    expect(styles).toContain('@media (prefers-reduced-motion: reduce)')
    expect(styles).toContain(':focus-visible')

    const themeButtonState = styles.match(/\.themeToggle:hover\s*\{([^}]*)\}/)
    expect(themeButtonState?.[1] ?? '').not.toContain('background')
    expect(styles).toContain('.themeLightOnly')
    expect(styles).toContain('.themeDarkOnly')
    expect(styles).toContain(":global([data-mantine-color-scheme='light']) .themeLightOnly")
    expect(styles).toContain(":global([data-mantine-color-scheme='dark']) .themeDarkOnly")
  })

  it('uses dark as the shared app default', async () => {
    const envSource = await readFile(join(process.cwd(), 'utils', 'env.ts'), 'utf8')
    const localEnv = await readFile(join(process.cwd(), '.env'), 'utf8')
    const localOverride = await readFile(join(process.cwd(), '.env.local'), 'utf8')

    expect(envSource).toContain("process.env.NEXT_PUBLIC_COLOR_SCHEME || 'dark'")
    expect(localEnv).toContain('NEXT_PUBLIC_COLOR_SCHEME=dark')
    expect(localOverride).toContain('NEXT_PUBLIC_COLOR_SCHEME=dark')
  })

  it('switches the brand asset and exposes an accessible theme toggle', async () => {
    const header = await readFile(join(process.cwd(), 'components', 'PageHeader.tsx'), 'utf8')

    expect(header).toContain('className={classes.themeLightOnly}')
    expect(header).toContain('className={classes.themeDarkOnly}')
    expect(header).toContain('src="/images/logo.svg"')
    expect(header).toContain('src="/images/logo-dark.svg"')
    expect(header).toContain('aria-label="Hanzi Studio"')
    expect(header).toContain('aria-label="Toggle color scheme"')
    expect(header).not.toContain('aria-pressed')
    expect(header).not.toContain('theme:')
    expect(header).toContain('alt=""')
    expect(header).not.toContain('<span>Theme</span>')
    expect(header).toContain('<IoMoonOutline className={classes.themeLightOnly} aria-hidden size={20} />')
    expect(header).toContain('<IoSunnyOutline className={classes.themeDarkOnly} aria-hidden size={20} />')
    expect(header).toContain('href={github}')
    expect(header).not.toContain('Tooltip')
  })
})
