export const CHARACTER_MESH_EXTRUSION_DEPTH_MIN = 1
export const CHARACTER_MESH_EXTRUSION_DEPTH_MAX = 100
export const CHARACTER_MESH_EXTRUSION_DEPTH_NORMALIZED_PER_UNIT = 0.01

export const CHARACTER_MESH_THICKNESS_MIN = -10
export const CHARACTER_MESH_THICKNESS_MAX = 10
export const CHARACTER_MESH_THICKNESS_NORMALIZED_PER_UNIT = 0.04

export const CHARACTER_MESH_BEVEL_MIN = 0
export const CHARACTER_MESH_BEVEL_MAX = 20
export const CHARACTER_MESH_BEVEL_NORMALIZED_PER_UNIT = 0.0054

export const CHARACTER_MESH_TAPER_MIN = -10
export const CHARACTER_MESH_TAPER_MAX = 10
export const CHARACTER_MESH_TAPER_NORMALIZED_PER_UNIT = 0.1

export const CHARACTER_MESH_BEVEL_SEGMENTS = 6
export const CHARACTER_SHAPE_FLATTEN_DIVISIONS = 12
