import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

const studioDir = join(process.cwd(), 'components', 'studio')

describe('Phase 5D Studio terminal Studio layout contract', () => {
  it('uses a route-local terminal shell instead of the old AppShell workbench', async () => {
    const shellSource = await readFile(join(studioDir, 'StudioShell.tsx'), 'utf8')
    const mobileHeader = await readFile(join(studioDir, 'StudioMobileHeader.tsx'), 'utf8')
    const shellStyles = await readFile(join(studioDir, 'StudioShell.module.css'), 'utf8')
    const mobileTabs = await readFile(join(studioDir, 'StudioMobileTabs.tsx'), 'utf8')

    expect(shellSource).toContain('data-studio-terminal-shell')
    expect(shellSource).toContain('data-studio-theme')
    expect(shellSource).toContain('data-studio-left-panel')
    expect(shellSource).toContain('data-studio-preview')
    expect(shellSource).toContain('data-studio-right-panel')
    expect(mobileTabs).toContain('data-studio-mobile-tabs')
    expect(shellSource).toContain('StudioThemeToggle')
    expect(shellSource).toContain('Fullscreen')
    expect(shellSource).not.toContain('IoPauseOutline')
    expect(shellSource).not.toContain('IoPlayOutline')
    expect(shellSource).not.toContain('AppShell')
    expect(shellSource).toContain('StudioMobileHeader')
    expect(mobileHeader).toContain('aria-controls={MENU_ID}')
    expect(mobileHeader).toContain('aria-expanded={menuOpen}')
    expect(mobileHeader).toContain('className={classes.mobileMenuOverlay}\n            tabIndex={-1}')
    expect(mobileHeader).not.toContain('autoFocus')
    expect(shellStyles).not.toContain(".mobileMenuAction[aria-pressed='true']")
    expect(shellSource).not.toContain('PageHeader')
    expect(shellStyles).toContain("data-studio-theme='light'")
    expect(shellStyles).toContain("data-studio-theme='dark'")
    expect(shellStyles).toContain('grid-template-columns: 329px minmax(0, 1fr) 414px')
    expect(shellStyles).toContain('position: fixed')
    expect(shellStyles).toContain('inset: 0')
    expect(shellStyles).toContain('--studio-top-rail-height: 50px')
    expect(shellStyles).toContain('--studio-bottom-rail-height: 60px')
    expect(shellSource).toContain('previewTopRail')
    expect(shellStyles).toContain('max-height: 40vh')
  })

  it('moves mobile viewport actions into a branded header menu', async () => {
    const shellSource = await readFile(join(studioDir, 'StudioShell.tsx'), 'utf8')
    const mobileHeader = await readFile(join(studioDir, 'StudioMobileHeader.tsx'), 'utf8')
    const shellStyles = await readFile(join(studioDir, 'StudioShell.module.css'), 'utf8')

    expect(mobileHeader).toContain("import Link from 'next/link'")
    expect(mobileHeader).toContain('href="/"')
    expect(mobileHeader).toContain("src={theme === 'dark' ? '/images/logo-dark.svg' : '/images/logo.svg'}")
    expect(mobileHeader).toContain('IoMenuOutline')
    expect(mobileHeader).toContain('<span>Theme</span>')
    expect(mobileHeader).toContain('<span>Fullscreen</span>')
    expect(mobileHeader).toContain('{Math.round(previewZoom * 100)}%')
    expect(mobileHeader).toContain('>Reset</button>')
    expect(mobileHeader).toContain('>Fit</button>')
    expect(shellSource).toContain("handleFullscreen('[data-studio-terminal-shell]')")
    expect(shellSource).toContain("handleFullscreen('[data-studio-preview]')")
    expect(shellStyles).toMatch(/@media \(max-width: 900px\)[\s\S]*?\.previewTopRail,[\s\S]*?\.zoomHud \{[\s\S]*?display: none;/)
    expect(shellStyles).toMatch(/@media \(max-width: 900px\)[\s\S]*?\.previewCanvasFrame \{[\s\S]*?inset: 0;/)
  })

  it('matches the generated desktop preview rails and compact terminal rows', async () => {
    const canvasSource = await readFile(join(studioDir, 'StudioCanvas.tsx'), 'utf8')
    const rowSource = await readFile(join(studioDir, 'TerminalRows.tsx'), 'utf8')
    const sectionSource = await readFile(join(studioDir, 'TerminalSection.tsx'), 'utf8')
    const shellStyles = await readFile(join(studioDir, 'StudioShell.module.css'), 'utf8')

    expect(canvasSource).not.toContain('rendererStatus')
    expect(canvasSource).not.toContain('rendererMode')
    expect(canvasSource).toContain('className={classes.zoomSpacer}')
    expect(canvasSource).toContain('aria-label="Fit preview"')
    expect(rowSource.indexOf('{children}')).toBeLessThan(
      rowSource.indexOf('<span className={classes.controlValue}>{value}</span>'),
    )
    expect(rowSource).toContain('action?: ReactNode')
    expect(rowSource).toContain('className={classes.groupHeader}')
    expect(sectionSource).toContain("expanded ? '−' : '+'")
    expect(shellStyles).toContain('height: var(--studio-top-rail-height)')
    expect(shellStyles).toContain('height: var(--studio-bottom-rail-height)')
    expect(shellStyles).toContain('grid-template-columns: 142px minmax(0, 1fr) 44px')
    expect(shellStyles).toContain('@media (min-width: 901px) and (hover: hover) and (pointer: fine)')
    expect(shellStyles).toContain('.rowGroup > .groupHeader .sectionResetButton')
    expect(shellStyles).toContain('.rowGroup:hover > .groupHeader .sectionResetButton')
    expect(shellStyles).toContain('.rowGroup:focus-within > .groupHeader .sectionResetButton')
    expect(shellStyles).toContain('pointer-events: none')
    expect(shellStyles).toContain('pointer-events: auto')
  })

  it('keeps every Character option inside the popover scrollport', async () => {
    const characterPanel = await readFile(join(studioDir, 'CharacterPanel.tsx'), 'utf8')
    const shellStyles = await readFile(join(studioDir, 'StudioShell.module.css'), 'utf8')

    expect(characterPanel.match(/characterPopoverScroll/g)).toHaveLength(1)
    expect(characterPanel).toContain('data-scrollbar-visible={scrollbarVisible}')
    expect(characterPanel).toContain('onPointerEnter={() => setScrollbarVisible(true)}')
    expect(characterPanel).toContain('onPointerLeave={() => setScrollbarVisible(false)}')
    expect(characterPanel.indexOf('Country')).toBeLessThan(
      characterPanel.indexOf('characterPopoverScroll'),
    )
    expect(characterPanel.indexOf('<span>Year</span>')).toBeLessThan(
      characterPanel.indexOf('characterPopoverScroll'),
    )
    expect(shellStyles).toContain('height: min(34rem, calc(100dvh - 2rem))')
    expect(shellStyles).toContain('grid-template-rows: auto minmax(0, 1fr)')
    expect(shellStyles).toContain('.characterPopoverScroll')
    expect(shellStyles).toContain('overflow-y: auto')
    expect(shellStyles).toContain('.characterPopover > .characterSelector:first-child')
    expect(shellStyles).toContain('padding: 0 10px 10px')
    expect(shellStyles).toContain('.characterPopoverScroll::-webkit-scrollbar')
    expect(shellStyles).toContain('width: 3px')
    expect(shellStyles).toContain('@supports not selector(::-webkit-scrollbar)')
    const characterScrollbarFallback = shellStyles.slice(
      shellStyles.indexOf('@supports not selector(::-webkit-scrollbar)'),
      shellStyles.indexOf('.characterPopoverScroll::-webkit-scrollbar'),
    )
    expect(characterScrollbarFallback).toContain('scrollbar-width: thin')
    expect(characterScrollbarFallback).toContain('scrollbar-color: transparent transparent')
    expect(shellStyles).toContain(".characterPopoverScroll[data-scrollbar-visible='true']::-webkit-scrollbar-thumb")
    expect(shellStyles).toContain('.characterPopoverScroll::-webkit-scrollbar-thumb:hover')
    expect(shellStyles).toContain('background-color: transparent')
    expect(shellStyles).toContain('var(--studio-text-bright) 55%')
    expect(shellStyles).toContain('var(--studio-text-bright) 85%')
    expect(shellStyles).toContain('transition: background-color 160ms ease')
  })

  it('has dedicated desktop panels and complete mobile tabs', async () => {
    const shellSource = await readFile(join(studioDir, 'StudioShell.tsx'), 'utf8')
    const leftPanel = await readFile(join(studioDir, 'StudioLeftPanel.tsx'), 'utf8')
    const rightPanel = await readFile(join(studioDir, 'StudioRightPanel.tsx'), 'utf8')
    const shellStyles = await readFile(join(studioDir, 'StudioShell.module.css'), 'utf8')
    const mobileTabs = await readFile(join(studioDir, 'StudioMobileTabs.tsx'), 'utf8')

    expect(leftPanel).toContain('CharacterPanel')
    expect(leftPanel).toContain('Input')
    expect(leftPanel).toContain('Effects')
    expect(leftPanel).toContain('StudioMotionPanel')
    expect(leftPanel).toContain('3D Motion')
    expect(leftPanel).toContain('Presets')
    expect(leftPanel).toContain('STUDIO_EFFECTS')
    expect(leftPanel).not.toContain('id="animation"')
    expect(leftPanel.indexOf('title="Input"')).toBeLessThan(leftPanel.indexOf('title="Effects"'))
    expect(leftPanel.indexOf('title="Effects"')).toBeLessThan(leftPanel.indexOf('title="Presets"'))
    expect(rightPanel).toContain('Settings')
    expect(rightPanel).toContain('Processing')
    expect(rightPanel).toContain('Post-Processing')
    expect(rightPanel).toContain('action={group.title ? (')
    expect(rightPanel).toContain('resetAsciiPrimaryGroup')
    expect(rightPanel).toContain('action={(')
    expect(rightPanel).toContain('id="processing"')
    expect(rightPanel).toContain('getStudioProcessingGroups(selectedEffectId)')
    expect(rightPanel).toContain('onClick={resetAsciiAdjustments}')
    expect(rightPanel).toContain('onClick={resetAsciiColor}')
    expect(rightPanel).toContain('brightness: DEFAULT_ASCII_STATE.brightness')
    expect(rightPanel).toContain('gamma: DEFAULT_ASCII_STATE.gamma')
    expect(rightPanel).toContain('group.controls.forEach')
    expect(shellStyles).not.toContain('.adjustmentsReset')
    expect(rightPanel).toContain('className={classes.postProcessingGroups}')
    expect(rightPanel).toContain('renderPostProcessingSettings')
    expect(rightPanel).toContain('className={classes.postProcessingGroup}')
    expect(rightPanel).toContain('group.controls.slice(1).forEach')
    expect(rightPanel).not.toContain('Reset all')
    expect(leftPanel).not.toContain('Reset all')
    expect(rightPanel).toContain('>\n            Reset\n')
    expect(shellStyles).toMatch(/\.meshDeformSection > \.inputGroupReset \{[\s\S]*?right: 8px;[\s\S]*?height: 30px;[\s\S]*?display: flex;[\s\S]*?align-items: center;/)
    expect(shellStyles).toMatch(/\.postProcessingGroup > \.inputGroupReset \{[\s\S]*?right: 8px;[\s\S]*?height: 30px;[\s\S]*?display: flex;[\s\S]*?align-items: center;/)
    expect(shellStyles).toMatch(/\.postProcessingGroup \{[\s\S]*?border: 1px solid var\(--studio-border\);/)
    expect(shellStyles).toContain(".postProcessingGroup[data-enabled='true']:hover > .inputGroupReset")
    expect(shellStyles).toMatch(/\.leftPanel \{[\s\S]*?padding-bottom: 40px;/)
    expect(shellStyles).toMatch(/\.rightContent \{[\s\S]*?padding-bottom: 40px;/)
    expect(rightPanel).toContain('Export')
    expect(rightPanel).toContain('title?: string')
    expect(rightPanel).toContain("title = 'Settings'")
    expect(mobileTabs).toContain('Input')
    expect(mobileTabs).toContain('Effects')
    expect(mobileTabs).toContain("id: 'model'")
    expect(mobileTabs).toContain("id: 'settings'")
    expect(mobileTabs.indexOf("id: 'model'")).toBeLessThan(mobileTabs.indexOf("id: 'effects'"))
    expect(mobileTabs.indexOf("id: 'effects'")).toBeLessThan(mobileTabs.indexOf("id: 'settings'"))
    expect(mobileTabs).toContain('StudioModelPanel')
    expect(mobileTabs).toContain('StudioModelDeformPanel')
    expect(mobileTabs).toContain('StudioRightPanel includeExport={false} title="Controllers"')
    expect(mobileTabs).toContain('StudioMotionPanel')
    expect(mobileTabs).not.toContain("id: 'animation'")
    expect(mobileTabs).toContain('Export')
    expect(mobileTabs).toContain('data-studio-mobile-tabs')
    expect(mobileTabs).toContain('aria-pressed={mobileTab === id}')
    expect(shellSource).not.toContain('StudioSettingsSheet')
  })
})
