import type { NextPage } from 'next'
import Head from 'next/head'
import { Divider, Group, AspectRatio } from '@mantine/core'
import { ScrollArea, Center, createStyles } from '@mantine/core'
import ToolStack from 'components/ToolStack'
import SvgItem from 'components/SvgItem'

const useStyles = createStyles((theme) => ({
  box: {
    padding: 20,
    height: '100vh',
  },
}))

type Props = {}

const Home: NextPage<Props> = () => {
  const { classes } = useStyles()

  return (
    <>
      <Head>
        <title>Font NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Group spacing={0}>
          <ScrollArea
            className={classes.box}
            sx={{
              flex: '400px 0',
            }}
          >
            <ToolStack />
          </ScrollArea>

          <Divider orientation="vertical" />

          <Center className={classes.box} sx={{ flexGrow: 1 }}>
            <AspectRatio
              ratio={1}
              sx={(theme) => ({
                border: `1px solid ${theme.colors.gray[4]}`,
                width: '100%',
                maxWidth: 400,
              })}
            >
              <SvgItem />
            </AspectRatio>
          </Center>
        </Group>
      </main>
    </>
  )
}

export default Home

export async function getStaticProps() {
  return {
    props: {},
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 60 * 60 * 24, // In seconds
  }
}
